server:
  port: 8761

spring:
  application:
    name: discovery-service
  datasource:
    url: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5  # 상태 갱신 간격 (기본 30초)
    lease-expiration-duration-in-seconds: 5  # 만료 시간 (기본 90초)
  client:
    register-with-eureka: false
    fetch-registry: false
    renewal-threshold-update-interval-ms: 60000 # 임계값 업데이트 간격 (기본값: 15분)
    eviction-interval-timer-in-ms: 60000 # 인스턴스 만료 검사 간격 (기본값: 60초)
