apiVersion: v1
kind: Service
metadata:
  name: e-commerce-user-service
spec:
  selector:
    app: e-commerce-user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce-user-service
  template:
    metadata:
      labels:
        app: e-commerce-user-service
    spec:
      containers:
        - name: e-commerce-user-service
          image: hyejan/user-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 100Mi
              cpu: 70m
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
